service: powertools-lambda

provider:
  name: aws
  runtime: python3.12
  region: us-east-1

functions:
  powertools:
    handler: lambda_function.lambda_handler
    architecture: arm64
    layers:
    - arn:aws:lambda:${aws:region}:017000801446:layer:AWSLambdaPowertoolsPythonV3-python312-arm64:3
