name: Deploy layer to all regions

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      latest_published_version:
        description: "Latest PyPi published version to rebuild latest docs for, e.g. v1.22.0"
        default: "v1.22.0"
        required: true
  workflow_run:
    workflows: [ "Publish to PyPi" ]
    types:
      - completed


jobs:
  build-layer:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./layer
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.12'
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Set release notes tag
        run: |
          RELEASE_INPUT=${{ inputs.latest_published_version }}
          GITHUB_EVENT_RELEASE_TAG=${{ github.event.release.tag_name }}
          RELEASE_TAG_VERSION=${GITHUB_EVENT_RELEASE_TAG:-$RELEASE_INPUT}
          echo "RELEASE_TAG_VERSION=${RELEASE_TAG_VERSION:1}" >> $GITHUB_ENV
      - name: install cdk and deps
        run: |
          npm install -g aws-cdk@2.29.0
          cdk --version
      - name: install deps
        run: |
          pip install -r requirements.txt
      - name: CDK build
        run: cdk synth --context version=$RELEASE_TAG_VERSION -o cdk.out
      - name: zip output
        run: zip -r cdk.out.zip cdk.out
      - name: Archive CDK artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cdk-layer-artefact
          path: cdk.out.zip

  deploy-beta:
    needs:
      - build-layer
    uses: ./.github/workflows/reusable_deploy_layer_stack.yml
    with:
      stage: "BETA"
      artefact-name: "cdk-layer-artefact"
    secrets:
      target-account-role: arn:aws:iam::${{ secrets.LAYERS_BETA_ACCOUNT }}:role/${{ secrets.AWS_GITHUB_OIDC_ROLE }}

  deploy-prod:
    needs:
      - deploy-beta
    uses: ./.github/workflows/reusable_deploy_layer_stack.yml
    with:
      stage: "PROD"
      artefact-name: "cdk-layer-artefact"
    secrets:
      target-account-role: arn:aws:iam::${{ secrets.LAYERS_PROD_ACCOUNT }}:role/${{ secrets.AWS_GITHUB_OIDC_ROLE }}
