name: Lockdown untrusted workflows

on:
  push:
    paths:
      - ".github/workflows/**"
  pull_request:
    paths:
      - ".github/workflows/**"

jobs:
  enforce_pinned_workflows:
    name: Harden Security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Ensure 3rd party workflows have SHA pinned
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@4f094cd33d8008b5aa2490edee9a5866ff11c116 # v1.4.0
        with:
          # Trusted GitHub Actions and/or organizations
          allowlist: |
            aws-actions/
            actions/checkout
            actions/github-script
            actions/setup-node
            actions/setup-python
            actions/upload-artifact
            actions/download-artifact
            github/codeql-action/init
            github/codeql-action/analyze
            dependabot/fetch-metadata
